[package]
name = "discord-goobing"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls-native-roots", "charset", "h2"] }
tokio = { version = "1", features = ["full"] }

rayon = "1.10.0"